import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--dataset', required = False, help = 'cifar10|place365|imagenet|glomerulus')
parser.add_argument('--dataroot', required = False, help = 'ptah to raw images')
parser.add_argument('--testroot', required = False, help = 'path to test data')
parser.add_argument('--trainroot', help = 'path to train data')
parser.add_argument('--num_classes', default =10, type = int, help = 'num of image classes')
parser.add_argument('--arch', required = False, help = 'resnet18|cifar-net|' )
parser.add_argument('--epochs', default = 90, type = int, help = 'epoch to run')
parser.add_argument('--batch_size', default = 64, type = int, help = 'batch size')
parser.add_argument('--num_workers', default = 1, type = int, help = 'num of workers')
parser.add_argument('--lr', default = 0.01, type = float, help = 'initial learning rate')
parser.add_argument('--experiments', type = str, help="dir to save train model and log")
parser.add_argument('--imageSize', default = 225, help="image size")
parser.add_argument('--use_cuda', default = True, type=bool,help ='wheater in training phase')
parser.add_argument('--resume', default = False, type = str, help = "if use previous checkpoint")
opt = parser.parse_args()